describe("mern_", () => {
  it("tests mern_", () => {
    cy.viewport(626, 585);
    cy.visit("http://localhost:3000/");
    cy.get("a:nth-of-type(5) > button").click();
    cy.get("#name").click();
    cy.get("#name").type("jj");
    cy.get("#email").click();
    cy.get("#email").type("jj@yahoo.com");
    cy.get("#password").click();
    cy.get("#password").type("jjjjjj");
    cy.get("#root > div > div button").click();
    cy.get("div.MuiDialog-root button").click();
    cy.get("#email").click();
    cy.get("#email").type("jj@yahoo.com");
    cy.get("#password").click();
    cy.get("#password").type("jjjjjj");
    cy.get("#root > div > div button").click();
    cy.get("a:nth-of-type(5) > button").click();
    cy.get("#root > div > div a svg").click();
    cy.get("label input").click();
    cy.get("#root > div > div button").click();
    cy.get("a:nth-of-type(5) > button").click();
    cy.get("#root > div > div button").click();
    cy.get("label > span").click();
    cy.get("div.MuiCardContent-root").click();
    cy.get("#icon-button-file").type("C:\\fakepath\\orbit_avoid.png");
    cy.get("#name").click();
    cy.get("#name").type("clothings");
    cy.get("#description").click();
    cy.get("#description").type("dress");
    cy.get("div.MuiCardActions-root > button").click();
    cy.get("#root > div > div a svg").click();
    cy.get("#name").click();
    cy.get("#name").type("clothings45");
    cy.get("#root > div > div > div:nth-of-type(2) button").click();
    cy.get("label > span").click();
    cy.get("div.MuiCardContent-root").click();
    cy.get("#icon-button-file").type("C:\\fakepath\\ZoomVirtualBackground2022WIMCanada.jpeg");
    cy.get("#name").click();
    cy.get("#name").type("banner");
    cy.get("#multiline-flexible").click();
    cy.get("#multiline-flexible").type("pattern");
    cy.get("#category").click();
    cy.get("#category").type("kk");
    cy.get("#quantity").click();
    cy.get("#quantity").type("3");
    cy.get("#price").click();
    cy.get("#price").type("3");
    cy.get("div.MuiCardActions-root > button").click();
    cy.get("#root > div > div > div:nth-of-type(1) button").click();
    cy.get("a:nth-of-type(2) > button").click();
    cy.get("#root > div > div a:nth-of-type(3)").click();
    cy.get("#root > div > div > div.MuiGrid-root > div:nth-of-type(1) svg").click();
    cy.get("#root > div > div a:nth-of-type(2) > button").click();
    cy.get("a:nth-of-type(2) > button").click();
    cy.get("#root > div > div a:nth-of-type(5)").click();
    cy.get("#root > div > div svg").click();
    cy.get("#root > div > div a:nth-of-type(1) > button").click();
    cy.get("#_r_2f_").click();
    cy.get("#_r_2f_").type("dsd");
    cy.get("#_r_2g_").type("cgg@yahoo.com");
    cy.get("#_r_2h_").type("fyyg");
    cy.get("#_r_2i_").type("gygygy");
    cy.get("#_r_2j_").type("ffffy");
    cy.get("#_r_2k_").click();
    cy.get("#_r_2k_").type("canada");
    cy.get("div > div > a > button").click();
    cy.get("a:nth-of-type(3) > button").click();
    cy.get("span.MuiButton-icon > span > span").click();
    cy.get("a:nth-of-type(1) path").click();
    cy.get("a:nth-of-type(2) > button").click();
  });
});
//# recorderSourceMap=BCBDBEBFBGBHBIBJBKBLBMBNBOBPBQBRBSBTBUBVBWBXBYBZBaBbBcBdBeBfBgBBhBBiBBjBBkBBlBBmBBnBBoBBpBBqBBrBBsBBtBBuBBvBBwBBxBByBBzBB0BB1BB2BB3BB4BB5BB6BB7BB8BB9BA9BA9BB+BA+BA+BB/BA/BA/BBgCAgCAgCBhCBiCBjCBkCBlCBmCBnCB
